version: '3'

services:

 traefik:
   image: traefik:v2.11
   ports:
     - "80:80"
     - "8080:8080"
   command:
     - "--providers.file.filename=/dynamic.yaml"
     - "--entrypoints.web.address=:80"
     - "--api.insecure=true"
     - "--accesslog=true"
     - "--api.dashboard=true"
   labels:
     - "traefik.enable=true"
     - "traefik.http.routers.traefik.rule=Host(`treafik.interships.site`)"
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./dynamic.yaml:/dynamic.yaml 
 web1:
   image: nginx:1.25.4-alpine
   ports:
     - "81:80"
   volumes:
     - ./web1:/usr/share/nginx/html
     - ./web1/nginx.conf:/etc/nginx/nginx.conf
 web2:
   image: nginx:1.25.4-alpine
   ports:
     - "82:80"    
   volumes:
     - ./web2:/usr/share/nginx/html
     - ./web2/nginx.conf:/etc/nginx/nginx.conf
 web3:
   image: nginx:1.25.4-alpine
   ports:
     - "83:80"    
   volumes:
     - ./web3:/usr/share/nginx/html 
     - ./web3/nginx.conf:/etc/nginx/nginx.conf
 web4:
   image: nginx:1.25.4-alpine
   ports:
     - "84:80"
   volumes:
     - ./web4:/usr/share/nginx/html
     

